import "~/styles/globals.css";

import { Inter } from "next/font/google";
import Providers from "./providers";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`container m-2 font-sans ${inter.variable}`}>
        <p className="text-tiny m-8 font-bold uppercase">
          Thredd technical test
        </p>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
